#!/bin/bash
# This is a demo config to show some of the most important commands more easily.
# This is meant to be changed and configured, as it is intentionally kept sparse.
# For a more advanced configuration example see my dotfiles:
# https://github.com/FelixKratz/dotfiles

PLUGIN_DIR="$HOME/.config/sketchybar/plugins"

##### Bar Appearance #####
# Configuring the general appearance of the bar, these are only some of the
# options available. For all options see:
# https://felixkratz.github.io/SketchyBar/config/bar
# If you are looking for other colors, see the color picker:
# https://felixkratz.github.io/SketchyBar/config/tricks#color-picker

sketchybar --bar height=38        \
                 blur_radius=30   \
                 position=top     \
                 sticky=off       \
                 padding_left=5  \
                 padding_right=5 \
                 margin=10  \
                 y_offset=10 \
                 corner_radius=5\
                 color=0xff1e1e2e

##### Changing Defaults #####
# We now change some default values that are applied to all further items
# For a full list of all available item properties see:
# https://felixkratz.github.io/SketchyBar/config/items

sketchybar --default icon.font="JetBrainsMonoNL Nerd Font Mono:Bold:18.0"  \
                     icon.color=0xffcdd6f4                 \
                     label.font="JetBrainsMonoNL Nerd Font Mono:Bold:16.0" \
                     label.color=0xffcdd6f4                \
                     padding_left=5                        \
                     padding_right=5                       \
                     label.padding_left=4                  \
                     label.padding_right=4                 \
                     icon.padding_left=4                   \
                     icon.padding_right=4

##### Adding Mission Control Space Indicators #####
# Now we add some mission control spaces:
# https://felixkratz.github.io/SketchyBar/config/components#space----associate-mission-control-spaces-with-an-item
# to indicate active and available mission control spaces

SPACE_ICONS=("" "" "" "󰀑" "󰍹" "♪" "" "󰙯" "")


for i in "${!SPACE_ICONS[@]}"
do
  sid=$(($i+1))
  sketchybar --add space space.$sid left                                 \
             --set space.$sid associated_space=$sid                      \
                              icon="${SPACE_ICONS[i]}"                     \
                              background.border_color=0xfff38ba8                \
                              background.border_width=2                \
                              background.corner_radius=5                 \
                              padding_left=2                        \
                              padding_right=2                       \
                              background.height=30                       \
                              icon.padding_left=8                   \
                              icon.padding_right=8\
                              background.drawing=off                     \
                              label.drawing=off                          \
                              script="$PLUGIN_DIR/space.sh"              \
                              click_script="yabai -m space --focus $sid"
done

##### Adding Left Items #####
# We add some regular items to the left side of the bar
# only the properties deviating from the current defaults need to be set

sketchybar --add item space_separator left                         \
           --set space_separator icon=                            \
                                 padding_left=10                   \
                                 padding_right=10                  \
                                 label.drawing=off                 \
                                                                   \
           --add item front_app left                               \
           --set front_app       script="$PLUGIN_DIR/front_app.sh" \
                                 icon.drawing=off                  \
           --subscribe front_app front_app_switched

##### Adding Right Items #####
# In the same way as the left items we can add items to the right side.
# Additional position (e.g. center) are available, see:
# https://felixkratz.github.io/SketchyBar/config/items#adding-items-to-sketchybar

## Right Item Defaults

sketchybar --default \
                     label.padding_left=6                  \
                     label.padding_right=6                 \
                     icon.padding_left=10                   \
                     icon.padding_right=10\
                     icon.background.border_color=0xffffffff\
                     icon.background.border_width=2\
                     icon.background.color=0xffffffff\
                     icon.color=0xff000000\
                     icon.background.drawing=on\
                     icon.background.height=30\
                     icon.background.corner_radius=5\
                     label.background.border_color=0xffffffff\
                     label.background.border_width=2\
                     label.background.drawing=on\
                     label.background.height=30\
                     label.background.corner_radius=5\

# Some items refresh on a fixed cycle, e.g. the clock runs its script once
# every 10s. Other items respond to events they subscribe to, e.g. the
# volume.sh script is only executed once an actual change in system audio
# volume is registered. More info about the event system can be found here:
# https://felixkratz.github.io/SketchyBar/config/events


sketchybar --add item clock right                              \
           --set clock   update_freq=10                        \
                         icon=                                \
                         script="$PLUGIN_DIR/clock.sh"         \
                         icon.background.color=0xffa6e3a1      \
                         icon.background.border_color=0xffa6e3a1      \
                         label.background.border_color=0xffa6e3a1\
                                                               \
           --add item wifi right                               \
           --set wifi    script="$PLUGIN_DIR/wifi.sh"          \
                         icon=󰖩                                \
                         icon.background.color=0xfff9e2af      \
                         icon.background.border_color=0xfff9e2af      \
                         label.background.border_color=0xfff9e2af\
           --subscribe wifi wifi_change                        \
                                                               \
           --add item volume right                             \
           --set volume  script="$PLUGIN_DIR/volume.sh"        \
                         icon.background.color=0xff89b4fa      \
                         icon.background.border_color=0xff89b4fa      \
                         label.background.border_color=0xff89b4fa\
           --subscribe volume volume_change                    \
                                                               \
           --add item battery right                            \
           --set battery script="$PLUGIN_DIR/battery.sh"       \
                         update_freq=120                       \
                         icon.background.color=0xfff5c2e7      \
                         icon.background.border_color=0xfff5c2e7      \
                         label.background.border_color=0xfff5c2e7\
           --subscribe battery system_woke power_source_change

##### Finalizing Setup #####
# The below command is only needed at the end of the initial configuration to
# force all scripts to run the first time, it should never be run in an item script.

sketchybar --hotload on

sketchybar --update
