#!/bin/bash
# This is a demo config to show some of the most important commands more easily.
# This is meant to be changed and configured, as it is intentionally kept sparse.
# For a more advanced configuration example see my dotfiles:
# https://github.com/FelixKratz/dotfiles

PLUGIN_DIR="$HOME/.config/sketchybar/plugins"

##### Bar Appearance #####
# Configuring the general appearance of the bar, these are only some of the
# options available. For all options see:
# https://felixkratz.github.io/SketchyBar/config/bar
# If you are looking for other colors, see the color picker:
# https://felixkratz.github.io/SketchyBar/config/tricks#color-picker

sketchybar --bar height=40        \
                 blur_radius=30   \
                 position=bottom     \
                 sticky=off       \
                 padding_left=10  \
                 padding_right=10 \
                 color=0xff282828 \
                 y_offset=5      \
                 margin=10        \
                 corner_radius=10 \

##### Changing Defaults #####
# We now change some default values that are applied to all further items
# For a full list of all available item properties see:
# https://felixkratz.github.io/SketchyBar/config/items

sketchybar --default icon.font="JetBrainsMonoNL Nerd Font Mono:Bold:23.0"  \
                     icon.color=0xffcdd6f4                 \
                     label.font="JetBrainsMonoNL Nerd Font Mono:Semibold:20.0" \
                     label.color=0xffcdd6f4                \
                     padding_left=2                        \
                     padding_right=2                       \
                     label.padding_left=4                  \
                     label.padding_right=4                 \
                     icon.padding_left=10                   \
                     icon.padding_right=10\
                     background.corner_radius=5                 \
                     background.height=30                       \

##### Adding Mission Control Space Indicators #####
# Now we add some mission control spaces:
# https://felixkratz.github.io/SketchyBar/config/components#space----associate-mission-control-spaces-with-an-item
# to indicate active and available mission control spaces

sketchybar --add item space_separator left                         \
           --set space_separator icon=󰍹                            \
                                 label.drawing=off\
                                 background.color=0xfffabd2f\
                                 background.border_width=0\
                                 icon.color=0xff282828\

SPACE_ICONS=("" "" "" "󰀑" "󰒋" "♪" "" "󰙯" "")


for i in "${!SPACE_ICONS[@]}"
do
  sid=$(($i+1))
  sketchybar --add space space.$sid left                                 \
             --set space.$sid associated_space=$sid                      \
                              icon="${SPACE_ICONS[i]}"                     \
                              background.drawing=on                     \
                              label.drawing=off                          \
                              script="$PLUGIN_DIR/space.sh"              \
                              click_script="yabai -m space --focus $sid"\

done

##### Adding Left Items #####
# We add some regular items to the left side of the bar
# only the properties deviating from the current defaults need to be set


sketchybar --add item front_app center                             \
           --set front_app       script="$PLUGIN_DIR/front_app.sh" \
                                 icon.drawing=off                  \
           --subscribe front_app front_app_switched\

##### Adding Right Items #####
# In the same way as the left items we can add items to the right side.
# Additional position (e.g. center) are available, see:
# https://felixkratz.github.io/SketchyBar/config/items#adding-items-to-sketchybar

sketchybar --add event wmmode

# Some items refresh on a fixed cycle, e.g. the clock runs its script once
# every 10s. Other items respond to events they subscribe to, e.g. the
# volume.sh script is only executed once an actual change in system audio
# volume is registered. More info about the event system can be found here:
# https://felixkratz.github.io/SketchyBar/config/events

sketchybar --add item clock right                              \
           --set clock   update_freq=10                        \
                         script="$PLUGIN_DIR/clock.sh"         \
                         label.padding_left=10\
                         label.padding_right=10\
                         background.color=0xff383838\
                         background.border_width=2\
                         background.border_color=0xffd3869b

sketchybar --add item clock_label right                         \
           --set clock_label icon=                            \
                                 label.drawing=off\
                                 background.color=0xffd3869b\
                                 background.border_width=0\
                                 icon.color=0xff282828

sketchybar  --add item wifi right                               \
           --set wifi    script="$PLUGIN_DIR/wifi.sh"          \
                         icon.drawing=off\
                         label.padding_left=10\
                         label.padding_right=10\
                         background.color=0xff383838\
                         background.border_width=2\
                         background.border_color=0xff8ec07c\
           --subscribe wifi wifi_change

sketchybar --add item wifi_label right                         \
           --set wifi_label icon=󰖩                            \
                                 label.drawing=off\
                                 background.color=0xff8ec07c\
                                 background.border_width=0\
                                 icon.color=0xff282828

sketchybar --add item volume right                             \
           --set volume  script="$PLUGIN_DIR/volume.sh"        \
                                 icon.drawing=off\
                                 background.color=0xff458588\
                                 background.border_width=0\
                                 icon.color=0xff282828\
                                  label.padding_left=10\
                                  label.padding_right=10\
                                  background.color=0xff383838\
                                  background.border_width=2\
                                  background.border_color=0xff458588\
           --subscribe volume volume_change                    \

sketchybar --add item volume_icon right                             \
           --set volume_icon  script="$PLUGIN_DIR/volume_icon.sh"        \
                         label.drawing=off\
                         label.padding_left=10\
                         label.padding_right=10\
                         background.color=0xff458588\
                         icon.color=0xff282828\
           --subscribe volume_icon volume_change                    \


sketchybar  --add item wm right                               \
           --set wm    script="$PLUGIN_DIR/wm.sh"          \
                         icon.drawing=off\
                         label.padding_left=10\
                         label.padding_right=10\
                         background.color=0xff383838\
                         background.border_width=2\
                         background.border_color=0xfffb4934\
           --subscribe wm space_change\
           --subscribe wm wmmode\

sketchybar --add item wm_icon right                         \
           --set wm_icon icon=󱂬                            \
                                 label.drawing=off\
                                 background.color=0xfffb4934\
                                 background.border_width=0\
                                 icon.color=0xff282828

##### Finalizing Setup #####
# The below command is only needed at the end of the initial configuration to
# force all scripts to run the first time, it should never be run in an item script.

sketchybar --hotload on
sketchybar --update
